name: umfile_utils-test
channels:
  - conda-forge
  - accessnri
  - defaults
dependencies:
  - python==3.10
  - cftime
  - ecgtools>=2023.7.13
  - intake==0.7.0
  - intake-dataframe-catalog>=0.2.4
  - intake-esm>=2023.11.10
  - jsonschema
  - pooch
  - pre-commit
  - pytest
  - xarray
  - mule
  - pip
  - pip:
    - codecov
    - pytest-cov
    - six 
