name: CD

on:
  push:
    tags:
      - '**'

env:
  CONDA_ARTIFACT_NAME: _conda_artifact

jobs:
  check-version:
    name: Check version
    runs-on: ubuntu-latest
    steps:
      - name: Check version
        uses: access-nri/actions/.github/actions/version-check@main
        with: 
          versioning-scheme: semver
    
  get-package-name:
    name: Get package name
    runs-on: ubuntu-latest
    outputs:
        package-name: ${{ steps.get-package-name.outputs.package-name }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Get name
        id: get-package-name
        run: |
          echo "package-name=$(yq '.project.name' pyproject.toml)" >> $GITHUB_OUTPUT

  ci:
    name: Run CI tests
    uses: ./.github/workflows/CI.yml

  release-conda-package:
    name: Build with conda and upload
    runs-on: ubuntu-latest
    needs: get-package-name
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
        with:
            fetch-tags: true
            fetch-depth: 0 

      - name: Setup conda build environment
        uses: mamba-org/setup-micromamba@7f29b8b80078b1b601dfa018b0f7425c587c63bb # v2.0.6
        with:
          environment-file: .conda/env_build.yml
          create-args: >-
            python=${{vars.PY_VERSION}}
      
      # conda build cannot get the version from setuptools_scm so we have 
      # to set it in an env var (PACKAGE_VERSION) prior to building 
      # and use it in the meta.yaml
      - name: Get package version
        id: get-version
        shell: micromamba-shell {0}
        run: |
          version=$(python3 -m setuptools_scm) 
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Build and upload conda package
        id: build-and-upload
        env:
          PACKAGE_VERSION: ${{ steps.get-version.outputs.version }}
        uses: ACCESS-NRI/action-build-and-upload-conda-packages@v3.1.0
        with:
          meta_yaml_dir: .conda
          user: ${{ secrets.ANACONDA_USER_NAME }}
          token: ${{ secrets.ANACONDA_TOKEN }}
          label: main
          conda_build_args: -c accessnri -c conda-forge -c nodefaults
      
      - name: Upload conda artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.CONDA_ARTIFACT_NAME }}
          path: ${{steps.build-and-upload.outputs.paths}}
    
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [get-package-name, release-conda-package]
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.CONDA_ARTIFACT_NAME }}
          path: artifact_dir

      - name: Create Release
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 #v2.3.3
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ needs.get-package-name.outputs.package-name }} ${{ github.ref_name }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: artifact_dir/*
    
  cleanup-on-failure:
    name: Cleanup on failure
    runs-on: ubuntu-latest
    needs: create-github-release
    # Run this job if any of the previous jobs failed, or if the workflow was cancelled
    if: always() && needs.create-github-release.result != 'success' || cancelled()
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-tags: true
          fetch-depth: 0 
      
      # Delete newly created tag
      - name: Cleanup tag
        run: |
          git push origin ':${{ github.ref }}'
          echo "A job in the current workflow failed. Tag '${{ github.ref }}' was deleted."
      
      # Delete newly created GitHub release
      - name: Cleanup GitHub release
        run: |
           gh release delete '${{ github.ref_name }}' && echo "GitHub release was deleted." || echo "No GitHub release '${{ github.ref_name }}' to delete."